### ISSUE TITLE
change the repo name to 'client'

### ISSUE THREAD

**Issue by superdweebie** [biblesoapopera/client#44]
'demo' isn't really the right name for this software any more. It is growing into a real product. 'client' seems the right name, because some time in the future there will also be a 'server'.

This needs be coordinated with the main bso site. Changing repo name will break inbound links.

**Comment by 90084** [comment]
no prob, let me know of the new URL and time of change and I can coordinate main website.

**Comment by superdweebie** [comment]
@90084 can we knock this one over? the new url will be http://biblesoapopera.github.io/client. Tell me when you are ready to make the change, and I'll do it from this end.

**Comment by 90084** [comment]
Sure, the change is ready, I'll activated on your go.

**Comment by superdweebie** [comment]
Done

ping @90084
